Header and menu
saeraa/next-tomten pull request #8
Opened 2023-05-18 19:00 UTC by davidlidebrandt

![screenshot-header-and-menu](https://github.com/saeraa/next-tomten/assets/70521806/e72dddcc-9fad-46a3-aa0c-30c92366af90)

Remade the header and menu from the previous project, I used pretty much all the styling from the old code with some minor changes. As previously discussed the search function was not implemented.

2023-05-18 21:52 UTC, ved0 requested changes
Some changes need to be done before the merge.
But all in all, works good and looks good!
Good work :)

2023-05-18 21:52 UTC, ved0 commented on src/components/dropDownItem/DropDownItem.js
> +          <i class="fa fa-caret-down"></i>
className instead of class :)

2023-05-18 21:52 UTC, ved0 commented on src/components/dropDownItem/DropDownItem.js
> +            return <Link href={item.href}>{item.text}</Link>;
need to put a key element inside the <Link> element so react doesnt complain. 
 For example, like this, <Link key={Math.random() * 13377331} >

2023-05-18 21:52 UTC, ved0 commented on src/components/menuDropDown/MenuDropDown.js
> +            idx={idx}
same here, need to put a key inside of the <DropDownItem> :)

2023-05-18 21:52 UTC, ved0 commented on src/components/navBar/navBar.js
> +const SUB_MENU_LIST = [
Cool way of doing it! :)

2023-05-18 22:48 UTC, ved0 approved these changes
I think it looks good now and no errors 👍

2023-05-18 23:01 UTC, merged

2023-06-04 08:37 UTC, richardolsson reviewed
Nice work! I have left some feedback below. 😊

2023-06-04 08:37 UTC, richardolsson commented on src/components/menuDropDown/MenuDropDown.js
> +            key={Math.random() * 13377331}
Don't use _random_ keys. React requires keys to be able to identify what elements are the same across renders, e.g. to notice when the order of elements change (and not just consider them completely new elements). Using a random key means they will always be considered new elements every re-render, which is pretty much as bad as not having a key.

If the key is not useful to you, just use the index as the key.

2023-06-04 08:37 UTC, richardolsson commented on src/components/dropDownItem/DropDownItem.js
> +            return <Link key={Math.random() * 13377331} href={item.href}>{item.text}</Link>;
Same here, use index as key if you have nothing else unique to work with.

2023-06-04 08:37 UTC, richardolsson commented on src/components/navBar/navBar.js
> +          }`}
Nice use of state!

2023-06-04 08:37 UTC, richardolsson commented on src/components/navBar/navBar.js
> +        ></button>
When you have an empty element (with no children), I usually prefer to use self-closing tags, i.e. `<button/>` instead of `<button></button>`